### ISSUE TITLE
Выводит ноль вместо реально сыгранного времени в одну игру

### ISSUE THREAD

**Issue by Viktor2491** [DmitryMikita/GameStore_testing#1]
# Описание
При указании жанра игры должен показывать общее сыгранное время, но выводит нулевое значение

# Локация дефекта
https://github.com/DmitryMikita/GameStore_testing/blob/08c04aa046fb0db73de878ea7aaabc343526868b/src/main/java/ru/netology/Player.java#L47-L57

# Шаги воспроизведения
1. Открыть класс [PlayerTest](https://github.com/DmitryMikita/GameStore_testing/blob/cefdedddee4c0949470bd8995a7af42ed04ffdbd/src/test/java/ru/netology/PlayerTest.java) в IDEA
1. Запустить тест https://github.com/DmitryMikita/GameStore_testing/blob/cefdedddee4c0949470bd8995a7af42ed04ffdbd/src/test/java/ru/netology/PlayerTest.java#L10

*Ожидаемый результат:* Выводит сыгранное время в игру равное 3 часам
*Фактический результат:* Выводит нулевое значение

# Скриншот
![Нулевое значение](https://user-images.githubusercontent.com/105769907/183836473-e2bd41dc-03b4-4cba-9c5a-f3c40f7ea248.png)

# Окружение
* **Операционная система:** Windows 7 (64 - разрядная)
* **IDE:** IntelliJ IDEA Community Edition 2021.1.3 3Х64
* **Java:** OpenJDK 11

**Comment by DmitryMikita** [comment]
[Fixes](https://github.com/DmitryMikita/GameStore_testing/commit/0b85b368f83e36f185d609ed065049f4b23fd597) #1
