### ISSUE TITLE
Выводит ноль вместо реально сыгранного времени в две игры одного жанра

### ISSUE THREAD

**Issue by Viktor2491** [DmitryMikita/GameStore_testing#2]
# Описание
Выводит ноль вместо реально сыгранного времени в двух играх одного жанра

# Локация дефекта
https://github.com/DmitryMikita/GameStore_testing/blob/cefdedddee4c0949470bd8995a7af42ed04ffdbd/src/main/java/ru/netology/Player.java#L47-L57

# Шаги воспроизведения
1. Открыть класс [PlayerTest](https://github.com/DmitryMikita/GameStore_testing/blob/cefdedddee4c0949470bd8995a7af42ed04ffdbd/src/test/java/ru/netology/PlayerTest.java) в IDEA
1. Запустить тест https://github.com/DmitryMikita/GameStore_testing/blob/cefdedddee4c0949470bd8995a7af42ed04ffdbd/src/test/java/ru/netology/PlayerTest.java#L25

*Ожидаемый результат:* Выводит сыгранное время в игры одного жанра  равное 13 часам
*Фактический результат:* Выводит нулевое значение

# Скриншот
![Две игры одного жанра](https://user-images.githubusercontent.com/105769907/183840104-60fa6bb8-69bf-4d7e-985e-87dba4f4a7e3.png)

# Окружение
* **Операционная система:** Windows 7 (64 - разрядная)
* **IDE:** IntelliJ IDEA Community Edition 2021.1.3 3Х64
* **Java:** OpenJDK 11

**Comment by DmitryMikita** [comment]
[Fixes](https://github.com/DmitryMikita/GameStore_testing/commit/0b85b368f83e36f185d609ed065049f4b23fd597) #2
