### ISSUE TITLE
Программа не возвращает ошибку, если игра не была установлена

### ISSUE THREAD

**Issue by Viktor2491** [DmitryMikita/GameStore_testing#3]
# Описание
В методе     public int play(Game game, int hours) не возвращается ошибка, если игра не была установлена

# Локация дефекта
https://github.com/DmitryMikita/GameStore_testing/blob/cefdedddee4c0949470bd8995a7af42ed04ffdbd/src/main/java/ru/netology/Player.java#L35-L43

# Шаги воспроизведения
1. Открыть класс [PlayerTest](https://github.com/DmitryMikita/GameStore_testing/blob/cefdedddee4c0949470bd8995a7af42ed04ffdbd/src/test/java/ru/netology/PlayerTest.java) в IDEA
1. Запустить тест https://github.com/DmitryMikita/GameStore_testing/blob/cefdedddee4c0949470bd8995a7af42ed04ffdbd/src/test/java/ru/netology/PlayerTest.java#L46

*Ожидаемый результат:* Появляется сообщение - "игра не установлена"
*Фактический результат:* org.opentest4j.AssertionFailedError: Expected java.lang.RuntimeException to be thrown, but nothing was thrown

# Скриншот
![Uploading Исключение.png…]()

# Окружение
* **Операционная система:** Windows 7 (64 - разрядная)
* **IDE:** IntelliJ IDEA Community Edition 2021.1.3 3Х64
* **Java:** OpenJDK 11

**Comment by DmitryMikita** [comment]
[Fixes](https://github.com/DmitryMikita/GameStore_testing/commit/0b85b368f83e36f185d609ed065049f4b23fd597) #3
